### ISSUE TITLE
system cant find path

### ISSUE THREAD

**Issue by tentacen** [cocomelonc/2021-04-09-av-evasion-1-#1]
![image](https://user-images.githubusercontent.com/120128395/208325413-8054eb4d-35bb-4dec-b798-0e3d13a07ff7.png)
i have Mingw64 installed

**Comment by cocomelonc** [comment]
Please read my blog carefully. In the examples, I use kali linux with mingw installed as the attacking machine. Therefore, the command will not work, especially since you are redirecting everything to /dev/null. In the case of using windows OS, it is better to use visual studio. And before copy and paste commands, at least try to understand how it works, then there will be no stupid questions. thanks for reading my blog

**Comment by tentacen** [comment]
> Please read my blog carefully. In the examples, I use kali linux with mingw installed as the attacking machine. Therefore, the command will not work, especially since you are redirecting everything to /dev/null. In the case of using windows OS, it is better to use visual studio. And before copy and paste commands, at least try to understand how it works, then there will be no stupid questions. thanks for reading my blog

Oh i do understand how the code works, the fact that i never used linux and i didnt know that the command was for linux directly doesnt make me stupid. Thanks for info tho i will compile it with VS.
